### ISSUE TITLE
значение аллели MMP1 MMP3

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#1]
Для генов MMP1 и MMP3 нет значений аллелей
ММР3 5А/6А, для ММР1 _/С
![значение аллели](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/2f4cb683-3958-440d-854e-0f07a2bab984)

**Comment by babinyurii** [comment]
добавил аллели 5А, 6А, - (делеция) в список выбора для модели SingleNucPol
