### ISSUE TITLE
Вкладка Samples

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#12]
Добавить поисковую строку и фильтр по тесту
Отобразить в списке образца тест/тесты, которые указываются при добавления информации об образце
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/51159ec8-52c4-45a3-9a07-2210e072c5ed)

**Comment by babinyurii** [comment]
фильтр по тесту добавил. остальное чуть позже
