### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#16]
Нельзя дробную концентрацию ДНК забить
Сейчас можно забить Lab ID и на латинице, и на английском, сохраняя ошибку не выдает, чтобы в будущем не было ошибок, сделать так, чтобы только по англ можно было забить
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/09b8836e-ec95-4a12-b298-bb39e9a0e609)

**Comment by babinyurii** [comment]
кажется, детекция языка происходит в браузере. пока это сделать не получится. можно добавить подпись и/или ограничение на используемые символы: только английский алфавит, например, числа и нижнее подчеркивание.
