### ISSUE TITLE
Report rule two snps

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#17]
Разобраться с report rule 
Создаешь другое правило для другого теста с маркерами, на которые уже правило, выходит ошибка с порядком правила 
Кажется он считывает порядок правила не на тест, а количество созданных правил вообще
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/37bffbc9-35cf-4948-aa75-dcb5c3fed181)

**Comment by kortnata97** [comment]
> Разобраться с report rule Создаешь другое правило для другого теста с маркерами, на которые уже правило, выходит ошибка с порядком правила Кажется он считывает порядок правила не на тест, а как порядок созданных всех правил, так как создаешь новое правило с другими совершенно маркерами и для другого теста, выдает ошибку на 1-4 oder in conclusion
 ![image](https://private-user-images.githubusercontent.com/159890872/305905145-37bffbc9-35cf-4948-aa75-dcb5c3fed181.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzkxMDMsIm5iZiI6MTcwODMzODgwMywicGF0aCI6Ii8xNTk4OTA4NzIvMzA1OTA1MTQ1LTM3YmZmYmM5LTM1Y2YtNDk0OC1hYTc1LWRjYjVjM2ZlZDE4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOVQxMDMzMjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NGM0N2VmNzRkN2U3Mjk1MTVhZGE1MmNiYmVhYTk3NTkxZGJlMWM1OTFmOWIxNGZjZGM4ZmJiMDA4NjJiMDQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5n9pshHCrLRPn2FgZOfZfRxKHQn-TAWq3fxU0PVeWx0)

**Comment by kortnata97** [comment]
Даже добавляя в правило еще один тест, ругается на порядок
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/8c85783c-1a7b-45f0-908a-42ac9089d54f)
Меняешь номер, сохраняет

**Comment by kortnata97** [comment]
Кажется номер oder in conclusion это как номер просто rule, который ты создаешь и да порядок в выводе теста сохраняется, но нельзя двум разным правилам для разных тестов присвоить Oder in conclusin, например 1 или одинаковый, выводит ошибку и говорит, что "правило отчета с таким номером уже существует выберите другой номер"

**Comment by babinyurii** [comment]
так, это надо проверить вручную. похоже, вопрос решился, когда я решал другой. теперь он не следит за порядком правил при создании правила. просто нужно будет их правильно выставить вручную.

**Comment by kortnata97** [comment]
Он не следит за порядком правил, надо следить самим, за их выставлением их порядка
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/e1fe853c-6531-4549-a678-0d78523f687f)
Вопрос можно ли сделать, чтобы он следил за порядком? Так как если будет больше тестов в какой-то момент можно ошибиться и в дальнейшем только самим-вручную проверять порядки

**Comment by kortnata97** [comment]
В conclusion for report выводы для пациента выходят по порядку создания правила, а не по Order in conclusion
