### ISSUE TITLE
SNP results

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#18]
Добавить подпись, что результат забивается по порядку аллели, то есть, если в маркере 1 аллель - Т, 2 аллель - C, забивать результат TC, если СТ, то выходит ошибка
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/31a73fae-94ad-41d7-9bf2-2a3e14629d9b)

**Comment by babinyurii** [comment]
сделал
