### ISSUE TITLE
Порядок отделов

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#19]
Кажется так логичнее, когда работаешь с программой от добавления маркеров и создания теста до добавления пациента и вывода результатов
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/1b275a69-1cd7-496e-a2d3-cd8b5639a9d1)

**Comment by babinyurii** [comment]
порядок отделов  внутри основного приложения samples and results изменен. С остальным пока не ясно, что делать. Пока закрываю, если будет очень нужно, откроем вопрос заново
