### ISSUE TITLE
Delete sample

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#20]
Сложная цепочка удаление образца 
Можно создать образец, не указывая тест, и удалить его спокойно
Стандартно создаешь Sample, указываешь все нужные поля и **главное тест**, позже хочешь удалить образец, программа тебе не дает этого сделать, пока не будут удалены все элементы связанные с Sample
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/40015a0f-4687-47f3-a25d-9d3d28e97133)
То есть только после удаления SNP results Sample, conclusion for report если забила результат и он есть, удаления теста в самом Sample, ты только после этого можешь удалить Sample
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/989a5329-69ea-46f4-963b-c08b40f04884)
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/fb05a5b8-67eb-4206-8b5c-0ca18e07f3d4)

**Comment by babinyurii** [comment]
теперь удалять можно. пока сменился интерфейс на добавление маркера для кита. по умолчанию будет пока такой, если станет неудобно, попробуем изменить. но это на потом.

**Comment by babinyurii** [comment]
теперь при удалении образца не должен удаляться kit.
но результаты связанные с образцом удаляться должны: иначе повиснут и непонятно, к чему относятся
