### ISSUE TITLE
Conclusion for report/ report rules

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#22]
Обновление conclusion for report происходит, только после удаления и заново ввода данных маркеров
Создаешь sample, вбил результат маркеров, смотришь вывод, а там ошибка, идешь исправлять в Report rules: conclusion for genotype combinations, сохраняешь, смотришь вывод опять, а он не исправился/ не обновился.
Приходится удалять conclusion for patient, заново вбивать значение маркеров и только после этого вывод обновляется

**Comment by babinyurii** [comment]
это фича )
вся логика создания репорта лежит в точке сохранения образца. 
по идее тексты для комбинаций генотипов, привязанные к правилу, лежат себе и лежат, просто хранятся в таблицах. программа лезет туда только когда сохраняется последний результат по пациенту. 
допустим, мы решим обновить какие-то conlusion for genotypes combinations. И если будет работать триггер на проверку всех заключений, то придется перезаписать все сохраненные в базе репорты. Тут получается, два плохих момента: мы лезем в базу и если у нас много пациентов - то это долгая возня и перезаписывание. Кроме того, если заключение уже ушло пациенту, его не надо менять. И даже если кто-то захочет повторно получить заключение (что вряд ли в наших условиях) странно выдавать ему измененный репорт: он может сравнить старый и новый и у него и врача будет каша в голове. Но можно и выдать с оговоркой: у нас изменился репорт - перезаписать образцы.

**Comment by babinyurii** [comment]
Итак, если мы изменили текст для комбинации генотипов, репорт программа не трогает.
Как изменить репорт после изменения текста для комбинации генотипов:
- заходим в любой результат для данного пациента и просто нажимаем кнопку SAVE: программа тогда увидит что сохранился последний результат и полезет записывать репорт - и перезапишет его с обновленными данными.

Попробуй так сделать: если получится, закрываем вопрос

**Comment by kortnata97** [comment]
Обновляется, даже если сохраняешь результат маркера, для которого нет правила
