### ISSUE TITLE
Add Sample

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#23]
Может сделать обязательным полем добавление теста для sample, а то сейчас можно сохранить пациента и без теста
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/3b326710-7a0a-4cec-a21c-8f72eb776fc5)

**Comment by babinyurii** [comment]
Смысл в том, чтоб можно было добавить пациента, сохранить его, а с тестом можно определиться позже. Это для удобства сделано.
