### ISSUE TITLE
Доработка сохранения и изменения правил

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#3]
При изменении созданного правила, например название, пишет ошибку
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/5f2b5360-5841-462d-8776-80ccb7f6dafc)

При изменении, например порядка в заключении, сохраняет это как изменение текущего правила, а не создает новое
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/6687b23f-7f7f-42f7-aacc-99591470fb37)

**Comment by babinyurii** [comment]
Теперь можно изменять уже сохраненные правила. 
Он будет ругаться только в случае, если повторно сохраняется правило для одного и того же теста с одинаковыми снипами. Чтоб не получился дубль в базе. 

Проверь плиз, и закрой вопрос, если все ок
