### ISSUE TITLE
Тесты где есть результат выводиться по сочетанию генов

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#34]
Есть тест Epilation, в котором по большей части генов вывод идет по результату гена, но есть вывод по сочетанию результатов генов IL13 и IL4. Я создала правило для них, внесла все выводы для них, в conclusion for each SNP genotype тоже внесла вывод. Когда начала вносить результаты по Sample, то в случае IL13 все было нормально, а в случае IL4 ошибку
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/0b2f5aed-21e3-43b3-b42e-8f7b00560ef5)

**Comment by kortnata97** [comment]
Программа не подгружает правило сочетаний генов, он лишь смотрит на conclusion for each SNP genotype, что туда забито, то и выводиться и пока не забьется вывод по результату гена, то будет выдавать ошибку

**Comment by kortnata97** [comment]
1. Если в тесте есть вывод на сочетание генов, то ты создаешь правило на это сочетание и приходиться вносить вывод для генов отдельно - в conclusion for each SNP genotype, так как если не внесешь вывод по ним, то при заполнении результатов Sample будет выводить ошибку, описанную выше;
2. Программа подгружает вывод на правило и выводит выводы по отдельному SNP, только сначала выводиться просто вывод правила, а потом выводы по отдельным SNP
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/454c99c3-06c7-4238-8817-f85eb082cfad)

**Comment by kortnata97** [comment]
Получается программа это выводит, как 2 разных объекта, а не смотрит по SNP и сопоставляет выводы

**Comment by babinyurii** [comment]
проверить наличие объектов по заключениям в базе. если их нет, сформировать заключение с какой нибудь заглушкой типа: заключение не найдено в базе. пока чтоб просто проверить, как будет работать
