### ISSUE TITLE
SNP detection kit

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#36]
Программа не дает сохранить изменение в созданном detection kit
То есть создаешь тест, например, не знаешь в каком порядке у тебя должны быть выводs по SNP, или ошибся в категории тоже выдает ошибку, пишет, что выводы по данному маркеру уже есть
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/2a0ad8f5-b645-4c12-a905-f2d0d5963adb)

**Comment by babinyurii** [comment]
1. добавить в модель `DetectionKitMarkers` , в метод `save()` проверку: создается запись или редактируется. Если редактируется - не создавать по ней заключения. 
2. второй вариант: проверить, есть ли связанные с записью заключения - если они есть - не пересохранять их
3. убрать из модели `DetectionKitMarkers` метод `clean` или настроить его так, чтоб он не лез проверять количество записей
