### ISSUE TITLE
Добавление клинического значения для аллели ( на будущее)

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#4]
Добавить в редактор маркера клин. значение определенной аллели norm/mut

**Comment by babinyurii** [comment]
в редком случае аллель может иметь разное значение для разных применений. поэтому непонятно пока где хранить это значение norm/mut. Если бы между маркером и набором была промежуточная таблица manytomany , то можно было бы хранить там. удобнее, конечно, в самом маркере. надо поварить еще
