### ISSUE TITLE
Данные по маркерам и комбинации в правилах

### ISSUE THREAD

**Issue by kortnata97** [babinyurii/lab_genetic_reporter#7]
Был создан маркер с неправильными аллелями, с ним создали правило.
В этом маркере изменили аллели, сохранили изменения, но в программе остались старые значения аллелей и добавились новые и в правиле, где есть этот маркер есть варианты комбинации и со старыми значениями аллелей и с новыми, вместо 9, 18 комбинаций
Если удаляешь правило и создаешь его заново, то указаны в маркерах нужные аллели и 9 комбинаций, как надо
![image](https://github.com/babinyurii/lab_genetic_reporter/assets/159890872/cabe6de7-51a3-40ea-80bd-84d1a6bc5ac2)

**Comment by babinyurii** [comment]
Теперь чтобы обновить комбинации после исправления данных маркера, нужно заново сохранить правило: просто щелкнуть по кнопке save.
Но данные по маркерам должны быть проверены до внесения образцов. 
Если внести результат по образцу и после изменить аллели маркера, в базе останется старый результат образца и далее возможны ошибки в случае, если мы пойдем заново этот образец сохранять - тогда может сгенерироваться отчет, он увидит, что результат не совпадает с маркером и сломается.

в нашей первой версии пока это не исправить. нужно переделывать базу данных.

То есть первичная база, на которую все опирается: маркеры. Ее забиваем один раз и больше стараемся не трогать.

**Comment by kortnata97** [comment]
вроде все так и работает
